---

stages:
  - build
  - deploy

variables:
  RTSOPTS: "+RTS -N1"
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:8.6.5
    entrypoint: [""]
  stage: build
  script:
    - make setup clean all
    - mkdir -p public
    - cp -pr .stack-work/install/x86_64-linux/*/*/hpc/* public/
    - cp -pr .stack-work/dist/x86_64-linux/Cabal-*/doc/html/wordfrequency/* public/
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - .stack
      - .stack-work

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing pages ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
