---
stages:
  - build
  - deploy

variables:
  CABAL_DIR: ${CI_PROJECT_DIR}/.cabal

build:
  except:
    - tags
  image:
    name: frankhjung/haskell:9.6.7
    entrypoint: [""]
  stage: build
  script:
    - make clean setup check build test bench doc
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_NAME}-${CI_JOB_NAME}
    paths:
      - .cabal
      - dist-newstyle

pages:
  only:
    refs:
      - master
  image: alpine:latest
  stage: deploy
  script:
    - echo Publishing pages ...
  dependencies:
    - build
  artifacts:
    paths:
      - public
