# https://www.stackage.org/ ghc 8.4.4 => lts 12.26
# https://www.stackage.org/lts-12.26/
resolver: lts-12.26
flags: {}
allow-newer: true
packages:
  - '.'
extra-deps:
  - criterion-1.4.1.0
  - hspec-2.5.5
  - text-1.2.3.1
arch: x86_64
system-ghc: true

